version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=/app/data
    restart: unless-stopped
    volumes:
      - scores-data:/app/data

volumes:
  scores-data: